name: Build GoblinModMaker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Windows needed for proper dependency resolution

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'  # Using .NET 9

      - name: Restore dependencies
        run: dotnet restore GoblinModMaker.sln

      - name: Build GMMBackend
        run: dotnet build GMMBackend/GMMBackend.csproj --configuration Release

      - name: Move GMMBackend.dll to GMMLauncher bin
        run: |
          mkdir -p GMMLauncher/bin/Release/net9.0
          mv GMMBackend/bin/Release/net9.0/GMMBackend.dll GMMLauncher/bin/Release/net9.0/

      - name: Build GMMLauncher
        run: dotnet build GMMLauncher/GMMLauncher.csproj --configuration Release

      - name: Publish GMMLauncher EXE
        run: dotnet publish GMMLauncher/GMMLauncher.csproj --configuration Release --output PublishedApp --self-contained true -r win-x64

      - name: Upload Published Application
        uses: actions/upload-artifact@v4
        with:
          name: PublishedApp
          path: PublishedApp/
